/*
 * This file is generated by jOOQ.
 */
package net.stumpwiz.mrradb.model.tables.records;


import net.stumpwiz.mrradb.model.tables.Office;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class OfficeRecord extends UpdatableRecordImpl<OfficeRecord> implements Record4<Long, String, Double, Long>
{

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached OfficeRecord
     */
    public OfficeRecord()
    {
        super(Office.OFFICE);
    }

    /**
     * Create a detached, initialised OfficeRecord
     */
    public OfficeRecord(Long officeid, String title, Double officeprecedence, Long officebodyid)
    {
        super(Office.OFFICE);

        setOfficeid(officeid);
        setTitle(title);
        setOfficeprecedence(officeprecedence);
        setOfficebodyid(officebodyid);
    }

    @Override
    public Record1<Long> key()
    {
        return (Record1) super.key();
    }

    @Override
    public Row4<Long, String, Double, Long> fieldsRow()
    {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, Double, Long> valuesRow()
    {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1()
    {
        return Office.OFFICE.OFFICEID;
    }

    @Override
    public Field<String> field2()
    {
        return Office.OFFICE.TITLE;
    }

    @Override
    public Field<Double> field3()
    {
        return Office.OFFICE.OFFICEPRECEDENCE;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Field<Long> field4()
    {
        return Office.OFFICE.OFFICEBODYID;
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Long value1()
    {
        return getOfficeid();
    }

    @Override
    public String value2()
    {
        return getTitle();
    }

    @Override
    public Double value3()
    {
        return getOfficeprecedence();
    }

    @Override
    public Long value4()
    {
        return getOfficebodyid();
    }

    @Override
    public OfficeRecord value1(Long value)
    {
        setOfficeid(value);
        return this;
    }

    @Override
    public OfficeRecord value2(String value)
    {
        setTitle(value);
        return this;
    }

    @Override
    public OfficeRecord value3(Double value)
    {
        setOfficeprecedence(value);
        return this;
    }

    @Override
    public OfficeRecord value4(Long value)
    {
        setOfficebodyid(value);
        return this;
    }

    @Override
    public OfficeRecord values(Long value1, String value2, Double value3, Long value4)
    {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    @Override
    public Long component1()
    {
        return getOfficeid();
    }

    /**
     * Getter for <code>raj.office.officeid</code>.
     */
    public Long getOfficeid()
    {
        return (Long) get(0);
    }

    /**
     * Setter for <code>raj.office.officeid</code>.
     */
    public void setOfficeid(Long value)
    {
        set(0, value);
    }

    @Override
    public String component2()
    {
        return getTitle();
    }

    /**
     * Getter for <code>raj.office.title</code>.
     */
    public String getTitle()
    {
        return (String) get(1);
    }

    /**
     * Setter for <code>raj.office.title</code>.
     */
    public void setTitle(String value)
    {
        set(1, value);
    }

    @Override
    public Double component3()
    {
        return getOfficeprecedence();
    }

    /**
     * Getter for <code>raj.office.officeprecedence</code>.
     */
    public Double getOfficeprecedence()
    {
        return (Double) get(2);
    }

    /**
     * Setter for <code>raj.office.officeprecedence</code>.
     */
    public void setOfficeprecedence(Double value)
    {
        set(2, value);
    }

    @Override
    public Long component4()
    {
        return getOfficebodyid();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>raj.office.officebodyid</code>.
     */
    public Long getOfficebodyid()
    {
        return (Long) get(3);
    }

    /**
     * Setter for <code>raj.office.officebodyid</code>.
     */
    public void setOfficebodyid(Long value)
    {
        set(3, value);
    }
}
