/*
 * This file is generated by jOOQ.
 */
package net.stumpwiz.mrradb.model.tables.records;


import net.stumpwiz.mrradb.model.tables.Person;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * A resident, staff member, or any other individual serving in some office at
 * Mercy Ridge.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PersonRecord extends UpdatableRecordImpl<PersonRecord> implements Record7<Long, String, String, String, String, String, String>
{

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached PersonRecord
     */
    public PersonRecord()
    {
        super(Person.PERSON);
    }

    /**
     * Create a detached, initialised PersonRecord
     */
    public PersonRecord(Long personid, String first, String last, String email, String phone, String apt, String personimage)
    {
        super(Person.PERSON);

        setPersonid(personid);
        setFirst(first);
        setLast(last);
        setEmail(email);
        setPhone(phone);
        setApt(apt);
        setPersonimage(personimage);
    }

    /**
     * Getter for <code>raj.person.personid</code>.
     */
    public Long getPersonid()
    {
        return (Long) get(0);
    }

    /**
     * Setter for <code>raj.person.personid</code>.
     */
    public void setPersonid(Long value)
    {
        set(0, value);
    }

    /**
     * Getter for <code>raj.person.first</code>.
     */
    public String getFirst()
    {
        return (String) get(1);
    }

    /**
     * Setter for <code>raj.person.first</code>.
     */
    public void setFirst(String value)
    {
        set(1, value);
    }

    /**
     * Getter for <code>raj.person.last</code>.
     */
    public String getLast()
    {
        return (String) get(2);
    }

    /**
     * Setter for <code>raj.person.last</code>.
     */
    public void setLast(String value)
    {
        set(2, value);
    }

    /**
     * Getter for <code>raj.person.email</code>.
     */
    public String getEmail()
    {
        return (String) get(3);
    }

    /**
     * Setter for <code>raj.person.email</code>.
     */
    public void setEmail(String value)
    {
        set(3, value);
    }

    /**
     * Getter for <code>raj.person.phone</code>.
     */
    public String getPhone()
    {
        return (String) get(4);
    }

    /**
     * Setter for <code>raj.person.phone</code>.
     */
    public void setPhone(String value)
    {
        set(4, value);
    }

    /**
     * Getter for <code>raj.person.apt</code>.
     */
    public String getApt()
    {
        return (String) get(5);
    }

    /**
     * Setter for <code>raj.person.apt</code>.
     */
    public void setApt(String value)
    {
        set(5, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>raj.person.personimage</code>.
     */
    public String getPersonimage()
    {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>raj.person.personimage</code>.
     */
    public void setPersonimage(String value)
    {
        set(6, value);
    }

    @Override
    public Record1<Long> key()
    {
        return (Record1) super.key();
    }

    @Override
    public Row7<Long, String, String, String, String, String, String> fieldsRow()
    {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, String, String, String, String, String> valuesRow()
    {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1()
    {
        return Person.PERSON.PERSONID;
    }

    @Override
    public Field<String> field2()
    {
        return Person.PERSON.FIRST;
    }

    @Override
    public Field<String> field3()
    {
        return Person.PERSON.LAST;
    }

    @Override
    public Field<String> field4()
    {
        return Person.PERSON.EMAIL;
    }

    @Override
    public Field<String> field5()
    {
        return Person.PERSON.PHONE;
    }

    @Override
    public Field<String> field6()
    {
        return Person.PERSON.APT;
    }

    @Override
    public Field<String> field7()
    {
        return Person.PERSON.PERSONIMAGE;
    }

    @Override
    public Long component1()
    {
        return getPersonid();
    }

    @Override
    public String component2()
    {
        return getFirst();
    }

    @Override
    public String component3()
    {
        return getLast();
    }

    @Override
    public String component4()
    {
        return getEmail();
    }

    @Override
    public String component5()
    {
        return getPhone();
    }

    @Override
    public String component6()
    {
        return getApt();
    }

    @Override
    public String component7()
    {
        return getPersonimage();
    }

    @Override
    public Long value1()
    {
        return getPersonid();
    }

    @Override
    public String value2()
    {
        return getFirst();
    }

    @Override
    public String value3()
    {
        return getLast();
    }

    @Override
    public String value4()
    {
        return getEmail();
    }

    @Override
    public String value5()
    {
        return getPhone();
    }

    @Override
    public String value6()
    {
        return getApt();
    }

    @Override
    public String value7()
    {
        return getPersonimage();
    }

    @Override
    public PersonRecord value1(Long value)
    {
        setPersonid(value);
        return this;
    }

    @Override
    public PersonRecord value2(String value)
    {
        setFirst(value);
        return this;
    }

    @Override
    public PersonRecord value3(String value)
    {
        setLast(value);
        return this;
    }

    @Override
    public PersonRecord value4(String value)
    {
        setEmail(value);
        return this;
    }

    @Override
    public PersonRecord value5(String value)
    {
        setPhone(value);
        return this;
    }

    @Override
    public PersonRecord value6(String value)
    {
        setApt(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public PersonRecord value7(String value)
    {
        setPersonimage(value);
        return this;
    }

    @Override
    public PersonRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7)
    {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }
}
