/*
 * This file is generated by jOOQ.
 */
package net.stumpwiz.mrradb.model.tables.records;


import net.stumpwiz.mrradb.model.tables.Pto;
import org.jooq.Field;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.TableRecordImpl;

import java.time.LocalDate;


/**
 * VIEW
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PtoRecord extends TableRecordImpl<PtoRecord> implements
        Record18<Long, String, String, String, String, String, LocalDate, LocalDate, String, Long, Long, Long, String
                , Double, Long, Long, String, Double>
{

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached PtoRecord
     */
    public PtoRecord()
    {
        super(Pto.PTO);
    }

    /**
     * Create a detached, initialised PtoRecord
     */
    public PtoRecord(
            Long personid, String first, String last, String email, String phone, String apt, LocalDate start,
            LocalDate end, String ordinal, Long termpersonid, Long termofficeid, Long officeid, String title,
            Double officeprecedence, Long officebodyid, Long bodyid, String name, Double bodyprecedence)
    {
        super(Pto.PTO);

        setPersonid(personid);
        setFirst(first);
        setLast(last);
        setEmail(email);
        setPhone(phone);
        setApt(apt);
        setStart(start);
        setEnd(end);
        setOrdinal(ordinal);
        setTermpersonid(termpersonid);
        setTermofficeid(termofficeid);
        setOfficeid(officeid);
        setTitle(title);
        setOfficeprecedence(officeprecedence);
        setOfficebodyid(officebodyid);
        setBodyid(bodyid);
        setName(name);
        setBodyprecedence(bodyprecedence);
    }

    @Override
    public Row18<Long, String, String, String, String, String, LocalDate, LocalDate, String, Long, Long, Long, String
            , Double, Long, Long, String, Double> fieldsRow()
    {
        return (Row18) super.fieldsRow();
    }

    @Override
    public Row18<Long, String, String, String, String, String, LocalDate, LocalDate, String, Long, Long, Long, String
            , Double, Long, Long, String, Double> valuesRow()
    {
        return (Row18) super.valuesRow();
    }

    @Override
    public Field<Long> field1()
    {
        return Pto.PTO.PERSONID;
    }

    @Override
    public Field<String> field2()
    {
        return Pto.PTO.FIRST;
    }

    @Override
    public Field<String> field3()
    {
        return Pto.PTO.LAST;
    }

    @Override
    public Field<String> field4()
    {
        return Pto.PTO.EMAIL;
    }

    @Override
    public Field<String> field5()
    {
        return Pto.PTO.PHONE;
    }

    @Override
    public Field<String> field6()
    {
        return Pto.PTO.APT;
    }

    @Override
    public Field<LocalDate> field7()
    {
        return Pto.PTO.START;
    }

    @Override
    public Field<LocalDate> field8()
    {
        return Pto.PTO.END;
    }

    @Override
    public Field<String> field9()
    {
        return Pto.PTO.ORDINAL;
    }

    @Override
    public Field<Long> field10()
    {
        return Pto.PTO.TERMPERSONID;
    }

    @Override
    public Field<Long> field11()
    {
        return Pto.PTO.TERMOFFICEID;
    }

    @Override
    public Field<Long> field12()
    {
        return Pto.PTO.OFFICEID;
    }

    @Override
    public Field<String> field13()
    {
        return Pto.PTO.TITLE;
    }

    @Override
    public Field<Double> field14()
    {
        return Pto.PTO.OFFICEPRECEDENCE;
    }

    @Override
    public Field<Long> field15()
    {
        return Pto.PTO.OFFICEBODYID;
    }

    @Override
    public Field<Long> field16()
    {
        return Pto.PTO.BODYID;
    }

    @Override
    public Field<String> field17()
    {
        return Pto.PTO.NAME;
    }

    @Override
    public Field<Double> field18()
    {
        return Pto.PTO.BODYPRECEDENCE;
    }

    @Override
    public Long value1()
    {
        return getPersonid();
    }

    @Override
    public String value2()
    {
        return getFirst();
    }

    @Override
    public String value3()
    {
        return getLast();
    }

    @Override
    public String value4()
    {
        return getEmail();
    }

    @Override
    public String value5()
    {
        return getPhone();
    }

    @Override
    public String value6()
    {
        return getApt();
    }

    @Override
    public LocalDate value7()
    {
        return getStart();
    }

    @Override
    public LocalDate value8()
    {
        return getEnd();
    }

    @Override
    public String value9()
    {
        return getOrdinal();
    }

    @Override
    public Long value10()
    {
        return getTermpersonid();
    }

    @Override
    public Long value11()
    {
        return getTermofficeid();
    }

    @Override
    public Long value12()
    {
        return getOfficeid();
    }

    @Override
    public String value13()
    {
        return getTitle();
    }

    @Override
    public Double value14()
    {
        return getOfficeprecedence();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Long value15()
    {
        return getOfficebodyid();
    }

    @Override
    public Long value16()
    {
        return getBodyid();
    }

    @Override
    public String value17()
    {
        return getName();
    }

    @Override
    public Double value18()
    {
        return getBodyprecedence();
    }

    @Override
    public PtoRecord value1(Long value)
    {
        setPersonid(value);
        return this;
    }

    @Override
    public PtoRecord value2(String value)
    {
        setFirst(value);
        return this;
    }

    @Override
    public PtoRecord value3(String value)
    {
        setLast(value);
        return this;
    }

    @Override
    public PtoRecord value4(String value)
    {
        setEmail(value);
        return this;
    }

    @Override
    public PtoRecord value5(String value)
    {
        setPhone(value);
        return this;
    }

    @Override
    public PtoRecord value6(String value)
    {
        setApt(value);
        return this;
    }

    @Override
    public PtoRecord value7(LocalDate value)
    {
        setStart(value);
        return this;
    }

    @Override
    public PtoRecord value8(LocalDate value)
    {
        setEnd(value);
        return this;
    }

    @Override
    public PtoRecord value9(String value)
    {
        setOrdinal(value);
        return this;
    }

    @Override
    public PtoRecord value10(Long value)
    {
        setTermpersonid(value);
        return this;
    }

    @Override
    public PtoRecord value11(Long value)
    {
        setTermofficeid(value);
        return this;
    }

    @Override
    public PtoRecord value12(Long value)
    {
        setOfficeid(value);
        return this;
    }

    @Override
    public PtoRecord value13(String value)
    {
        setTitle(value);
        return this;
    }

    @Override
    public PtoRecord value14(Double value)
    {
        setOfficeprecedence(value);
        return this;
    }

    @Override
    public PtoRecord value15(Long value)
    {
        setOfficebodyid(value);
        return this;
    }

    @Override
    public PtoRecord value16(Long value)
    {
        setBodyid(value);
        return this;
    }

    @Override
    public PtoRecord value17(String value)
    {
        setName(value);
        return this;
    }

    @Override
    public PtoRecord value18(Double value)
    {
        setBodyprecedence(value);
        return this;
    }

    @Override
    public PtoRecord values(
            Long value1, String value2, String value3, String value4, String value5, String value6, LocalDate value7,
            LocalDate value8, String value9, Long value10, Long value11, Long value12, String value13, Double value14,
            Long value15, Long value16, String value17, Double value18)
    {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    @Override
    public Long component1()
    {
        return getPersonid();
    }

    /**
     * Getter for <code>raj.pto.personid</code>.
     */
    public Long getPersonid()
    {
        return (Long) get(0);
    }

    /**
     * Setter for <code>raj.pto.personid</code>.
     */
    public void setPersonid(Long value)
    {
        set(0, value);
    }

    @Override
    public String component2()
    {
        return getFirst();
    }

    /**
     * Getter for <code>raj.pto.first</code>.
     */
    public String getFirst()
    {
        return (String) get(1);
    }

    /**
     * Setter for <code>raj.pto.first</code>.
     */
    public void setFirst(String value)
    {
        set(1, value);
    }

    @Override
    public String component3()
    {
        return getLast();
    }

    /**
     * Getter for <code>raj.pto.last</code>.
     */
    public String getLast()
    {
        return (String) get(2);
    }

    /**
     * Setter for <code>raj.pto.last</code>.
     */
    public void setLast(String value)
    {
        set(2, value);
    }

    @Override
    public String component4()
    {
        return getEmail();
    }

    /**
     * Getter for <code>raj.pto.email</code>.
     */
    public String getEmail()
    {
        return (String) get(3);
    }

    /**
     * Setter for <code>raj.pto.email</code>.
     */
    public void setEmail(String value)
    {
        set(3, value);
    }

    @Override
    public String component5()
    {
        return getPhone();
    }

    /**
     * Getter for <code>raj.pto.phone</code>.
     */
    public String getPhone()
    {
        return (String) get(4);
    }

    /**
     * Setter for <code>raj.pto.phone</code>.
     */
    public void setPhone(String value)
    {
        set(4, value);
    }

    @Override
    public String component6()
    {
        return getApt();
    }

    /**
     * Getter for <code>raj.pto.apt</code>.
     */
    public String getApt()
    {
        return (String) get(5);
    }

    /**
     * Setter for <code>raj.pto.apt</code>.
     */
    public void setApt(String value)
    {
        set(5, value);
    }

    @Override
    public LocalDate component7()
    {
        return getStart();
    }

    /**
     * Getter for <code>raj.pto.start</code>.
     */
    public LocalDate getStart()
    {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>raj.pto.start</code>.
     */
    public void setStart(LocalDate value)
    {
        set(6, value);
    }

    @Override
    public LocalDate component8()
    {
        return getEnd();
    }

    /**
     * Getter for <code>raj.pto.end</code>.
     */
    public LocalDate getEnd()
    {
        return (LocalDate) get(7);
    }

    /**
     * Setter for <code>raj.pto.end</code>.
     */
    public void setEnd(LocalDate value)
    {
        set(7, value);
    }

    @Override
    public String component9()
    {
        return getOrdinal();
    }

    /**
     * Getter for <code>raj.pto.ordinal</code>.
     */
    public String getOrdinal()
    {
        return (String) get(8);
    }

    /**
     * Setter for <code>raj.pto.ordinal</code>.
     */
    public void setOrdinal(String value)
    {
        set(8, value);
    }

    @Override
    public Long component10()
    {
        return getTermpersonid();
    }

    /**
     * Getter for <code>raj.pto.termpersonid</code>.
     */
    public Long getTermpersonid()
    {
        return (Long) get(9);
    }

    /**
     * Setter for <code>raj.pto.termpersonid</code>.
     */
    public void setTermpersonid(Long value)
    {
        set(9, value);
    }

    @Override
    public Long component11()
    {
        return getTermofficeid();
    }

    /**
     * Getter for <code>raj.pto.termofficeid</code>.
     */
    public Long getTermofficeid()
    {
        return (Long) get(10);
    }

    /**
     * Setter for <code>raj.pto.termofficeid</code>.
     */
    public void setTermofficeid(Long value)
    {
        set(10, value);
    }

    @Override
    public Long component12()
    {
        return getOfficeid();
    }

    /**
     * Getter for <code>raj.pto.officeid</code>.
     */
    public Long getOfficeid()
    {
        return (Long) get(11);
    }

    /**
     * Setter for <code>raj.pto.officeid</code>.
     */
    public void setOfficeid(Long value)
    {
        set(11, value);
    }

    @Override
    public String component13()
    {
        return getTitle();
    }

    /**
     * Getter for <code>raj.pto.title</code>.
     */
    public String getTitle()
    {
        return (String) get(12);
    }

    /**
     * Setter for <code>raj.pto.title</code>.
     */
    public void setTitle(String value)
    {
        set(12, value);
    }

    @Override
    public Double component14()
    {
        return getOfficeprecedence();
    }

    /**
     * Getter for <code>raj.pto.officeprecedence</code>.
     */
    public Double getOfficeprecedence()
    {
        return (Double) get(13);
    }

    /**
     * Setter for <code>raj.pto.officeprecedence</code>.
     */
    public void setOfficeprecedence(Double value)
    {
        set(13, value);
    }

    @Override
    public Long component15()
    {
        return getOfficebodyid();
    }

    /**
     * Getter for <code>raj.pto.officebodyid</code>.
     */
    public Long getOfficebodyid()
    {
        return (Long) get(14);
    }

    /**
     * Setter for <code>raj.pto.officebodyid</code>.
     */
    public void setOfficebodyid(Long value)
    {
        set(14, value);
    }

    @Override
    public Long component16()
    {
        return getBodyid();
    }

    /**
     * Getter for <code>raj.pto.bodyid</code>.
     */
    public Long getBodyid()
    {
        return (Long) get(15);
    }

    /**
     * Setter for <code>raj.pto.bodyid</code>.
     */
    public void setBodyid(Long value)
    {
        set(15, value);
    }

    @Override
    public String component17()
    {
        return getName();
    }

    /**
     * Getter for <code>raj.pto.name</code>.
     */
    public String getName()
    {
        return (String) get(16);
    }

    /**
     * Setter for <code>raj.pto.name</code>.
     */
    public void setName(String value)
    {
        set(16, value);
    }

    @Override
    public Double component18()
    {
        return getBodyprecedence();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>raj.pto.bodyprecedence</code>. Field for ordering in reports and web pages.  Stored as double to
     * allow insertions of new bodies.
     */
    public Double getBodyprecedence()
    {
        return (Double) get(17);
    }

    /**
     * Setter for <code>raj.pto.bodyprecedence</code>. Field for ordering in
     * reports and web pages.  Stored as double to allow insertions of new
     * bodies.
     */
    public void setBodyprecedence(Double value)
    {
        set(17, value);
    }
}
