/*
 * This file is generated by jOOQ.
 */
package net.stumpwiz.mrradb.model.tables.records;


import net.stumpwiz.mrradb.model.tables.Term;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TermRecord extends UpdatableRecordImpl<TermRecord>
        implements Record5<LocalDate, LocalDate, String, Long, Long>
{

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached TermRecord
     */
    public TermRecord()
    {
        super(Term.TERM);
    }

    /**
     * Create a detached, initialised TermRecord
     */
    public TermRecord(LocalDate start, LocalDate end, String ordinal, Long termpersonid, Long termofficeid)
    {
        super(Term.TERM);

        setStart(start);
        setEnd(end);
        setOrdinal(ordinal);
        setTermpersonid(termpersonid);
        setTermofficeid(termofficeid);
    }

    @Override
    public Record2<Long, Long> key()
    {
        return (Record2) super.key();
    }

    @Override
    public Row5<LocalDate, LocalDate, String, Long, Long> fieldsRow()
    {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<LocalDate, LocalDate, String, Long, Long> valuesRow()
    {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<LocalDate> field1()
    {
        return Term.TERM.START;
    }

    @Override
    public Field<LocalDate> field2()
    {
        return Term.TERM.END;
    }

    @Override
    public Field<String> field3()
    {
        return Term.TERM.ORDINAL;
    }

    @Override
    public Field<Long> field4()
    {
        return Term.TERM.TERMPERSONID;
    }

    @Override
    public Field<Long> field5()
    {
        return Term.TERM.TERMOFFICEID;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public LocalDate value1()
    {
        return getStart();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public LocalDate value2()
    {
        return getEnd();
    }

    @Override
    public String value3()
    {
        return getOrdinal();
    }

    @Override
    public Long value4()
    {
        return getTermpersonid();
    }

    @Override
    public Long value5()
    {
        return getTermofficeid();
    }

    @Override
    public TermRecord value1(LocalDate value)
    {
        setStart(value);
        return this;
    }

    @Override
    public TermRecord value2(LocalDate value)
    {
        setEnd(value);
        return this;
    }

    @Override
    public TermRecord value3(String value)
    {
        setOrdinal(value);
        return this;
    }

    @Override
    public TermRecord value4(Long value)
    {
        setTermpersonid(value);
        return this;
    }

    @Override
    public TermRecord value5(Long value)
    {
        setTermofficeid(value);
        return this;
    }

    @Override
    public TermRecord values(LocalDate value1, LocalDate value2, String value3, Long value4, Long value5)
    {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    @Override
    public LocalDate component1()
    {
        return getStart();
    }

    /**
     * Getter for <code>raj.term.start</code>.
     */
    public LocalDate getStart()
    {
        return (LocalDate) get(0);
    }

    /**
     * Setter for <code>raj.term.start</code>.
     */
    public void setStart(LocalDate value)
    {
        set(0, value);
    }

    @Override
    public LocalDate component2()
    {
        return getEnd();
    }

    /**
     * Getter for <code>raj.term.end</code>.
     */
    public LocalDate getEnd()
    {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>raj.term.end</code>.
     */
    public void setEnd(LocalDate value)
    {
        set(1, value);
    }

    @Override
    public String component3()
    {
        return getOrdinal();
    }

    /**
     * Getter for <code>raj.term.ordinal</code>.
     */
    public String getOrdinal()
    {
        return (String) get(2);
    }

    /**
     * Setter for <code>raj.term.ordinal</code>.
     */
    public void setOrdinal(String value)
    {
        set(2, value);
    }

    @Override
    public Long component4()
    {
        return getTermpersonid();
    }

    /**
     * Getter for <code>raj.term.termpersonid</code>.
     */
    public Long getTermpersonid()
    {
        return (Long) get(3);
    }

    /**
     * Setter for <code>raj.term.termpersonid</code>.
     */
    public void setTermpersonid(Long value)
    {
        set(3, value);
    }

    @Override
    public Long component5()
    {
        return getTermofficeid();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>raj.term.termofficeid</code>.
     */
    public Long getTermofficeid()
    {
        return (Long) get(4);
    }

    /**
     * Setter for <code>raj.term.termofficeid</code>.
     */
    public void setTermofficeid(Long value)
    {
        set(4, value);
    }
}
