/*
 * This file is generated by jOOQ.
 */
package net.stumpwiz.mrradb.model.tables.records;


import net.stumpwiz.mrradb.model.tables.Body;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * An organizational unit at Mercy Ridge.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BodyRecord extends UpdatableRecordImpl<BodyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>raj.body.bodyid</code>.
     */
    public void setBodyid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>raj.body.bodyid</code>.
     */
    public Long getBodyid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>raj.body.bodyimage</code>. Name of the graphic file that
     * represents the body in reports and web pages.
     */
    public void setBodyimage(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>raj.body.bodyimage</code>. Name of the graphic file that
     * represents the body in reports and web pages.
     */
    public String getBodyimage() {
        return (String) get(1);
    }

    /**
     * Setter for <code>raj.body.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>raj.body.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>raj.body.mission</code>.
     */
    public void setMission(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>raj.body.mission</code>.
     */
    public String getMission() {
        return (String) get(3);
    }

    /**
     * Setter for <code>raj.body.bodyprecedence</code>. Field for ordering in
     * reports and web pages.  Stored as double to allow insertions of new
     * bodies.
     */
    public void setBodyprecedence(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>raj.body.bodyprecedence</code>. Field for ordering in
     * reports and web pages.  Stored as double to allow insertions of new
     * bodies.
     */
    public Double getBodyprecedence() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BodyRecord
     */
    public BodyRecord() {
        super(Body.BODY);
    }

    /**
     * Create a detached, initialised BodyRecord
     */
    public BodyRecord(Long bodyid, String bodyimage, String name, String mission, Double bodyprecedence) {
        super(Body.BODY);

        setBodyid(bodyid);
        setBodyimage(bodyimage);
        setName(name);
        setMission(mission);
        setBodyprecedence(bodyprecedence);
        resetChangedOnNotNull();
    }
}
