/*
 * This file is generated by jOOQ.
 */
package net.stumpwiz.mrradb.model.tables.records;


import net.stumpwiz.mrradb.model.tables.Office;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OfficeRecord extends UpdatableRecordImpl<OfficeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>raj.office.officeid</code>.
     */
    public void setOfficeid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>raj.office.officeid</code>.
     */
    public Long getOfficeid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>raj.office.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>raj.office.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>raj.office.officeprecedence</code>.
     */
    public void setOfficeprecedence(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>raj.office.officeprecedence</code>.
     */
    public Double getOfficeprecedence() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>raj.office.officebodyid</code>.
     */
    public void setOfficebodyid(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>raj.office.officebodyid</code>.
     */
    public Long getOfficebodyid() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OfficeRecord
     */
    public OfficeRecord() {
        super(Office.OFFICE);
    }

    /**
     * Create a detached, initialised OfficeRecord
     */
    public OfficeRecord(Long officeid, String title, Double officeprecedence, Long officebodyid) {
        super(Office.OFFICE);

        setOfficeid(officeid);
        setTitle(title);
        setOfficeprecedence(officeprecedence);
        setOfficebodyid(officebodyid);
        resetChangedOnNotNull();
    }
}
