/*
 * This file is generated by jOOQ.
 */
package net.stumpwiz.mrradb.model.tables.records;


import java.time.LocalDate;

import net.stumpwiz.mrradb.model.tables.Pto;

import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PtoRecord extends TableRecordImpl<PtoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>raj.pto.personid</code>.
     */
    public void setPersonid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>raj.pto.personid</code>.
     */
    public Long getPersonid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>raj.pto.first</code>.
     */
    public void setFirst(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>raj.pto.first</code>.
     */
    public String getFirst() {
        return (String) get(1);
    }

    /**
     * Setter for <code>raj.pto.last</code>.
     */
    public void setLast(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>raj.pto.last</code>.
     */
    public String getLast() {
        return (String) get(2);
    }

    /**
     * Setter for <code>raj.pto.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>raj.pto.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>raj.pto.phone</code>.
     */
    public void setPhone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>raj.pto.phone</code>.
     */
    public String getPhone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>raj.pto.apt</code>.
     */
    public void setApt(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>raj.pto.apt</code>.
     */
    public String getApt() {
        return (String) get(5);
    }

    /**
     * Setter for <code>raj.pto.start</code>.
     */
    public void setStart(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>raj.pto.start</code>.
     */
    public LocalDate getStart() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>raj.pto.end</code>.
     */
    public void setEnd(LocalDate value) {
        set(7, value);
    }

    /**
     * Getter for <code>raj.pto.end</code>.
     */
    public LocalDate getEnd() {
        return (LocalDate) get(7);
    }

    /**
     * Setter for <code>raj.pto.ordinal</code>.
     */
    public void setOrdinal(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>raj.pto.ordinal</code>.
     */
    public String getOrdinal() {
        return (String) get(8);
    }

    /**
     * Setter for <code>raj.pto.termpersonid</code>.
     */
    public void setTermpersonid(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>raj.pto.termpersonid</code>.
     */
    public Long getTermpersonid() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>raj.pto.termofficeid</code>.
     */
    public void setTermofficeid(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>raj.pto.termofficeid</code>.
     */
    public Long getTermofficeid() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>raj.pto.officeid</code>.
     */
    public void setOfficeid(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>raj.pto.officeid</code>.
     */
    public Long getOfficeid() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>raj.pto.title</code>.
     */
    public void setTitle(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>raj.pto.title</code>.
     */
    public String getTitle() {
        return (String) get(12);
    }

    /**
     * Setter for <code>raj.pto.officeprecedence</code>.
     */
    public void setOfficeprecedence(Double value) {
        set(13, value);
    }

    /**
     * Getter for <code>raj.pto.officeprecedence</code>.
     */
    public Double getOfficeprecedence() {
        return (Double) get(13);
    }

    /**
     * Setter for <code>raj.pto.officebodyid</code>.
     */
    public void setOfficebodyid(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>raj.pto.officebodyid</code>.
     */
    public Long getOfficebodyid() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>raj.pto.bodyid</code>.
     */
    public void setBodyid(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>raj.pto.bodyid</code>.
     */
    public Long getBodyid() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>raj.pto.name</code>.
     */
    public void setName(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>raj.pto.name</code>.
     */
    public String getName() {
        return (String) get(16);
    }

    /**
     * Setter for <code>raj.pto.bodyprecedence</code>. Field for ordering in
     * reports and web pages.  Stored as double to allow insertions of new
     * bodies.
     */
    public void setBodyprecedence(Double value) {
        set(17, value);
    }

    /**
     * Getter for <code>raj.pto.bodyprecedence</code>. Field for ordering in
     * reports and web pages.  Stored as double to allow insertions of new
     * bodies.
     */
    public Double getBodyprecedence() {
        return (Double) get(17);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PtoRecord
     */
    public PtoRecord() {
        super(Pto.PTO);
    }

    /**
     * Create a detached, initialised PtoRecord
     */
    public PtoRecord(Long personid, String first, String last, String email, String phone, String apt, LocalDate start, LocalDate end, String ordinal, Long termpersonid, Long termofficeid, Long officeid, String title, Double officeprecedence, Long officebodyid, Long bodyid, String name, Double bodyprecedence) {
        super(Pto.PTO);

        setPersonid(personid);
        setFirst(first);
        setLast(last);
        setEmail(email);
        setPhone(phone);
        setApt(apt);
        setStart(start);
        setEnd(end);
        setOrdinal(ordinal);
        setTermpersonid(termpersonid);
        setTermofficeid(termofficeid);
        setOfficeid(officeid);
        setTitle(title);
        setOfficeprecedence(officeprecedence);
        setOfficebodyid(officebodyid);
        setBodyid(bodyid);
        setName(name);
        setBodyprecedence(bodyprecedence);
        resetChangedOnNotNull();
    }
}
