/*
 * This file is generated by jOOQ.
 */
package net.stumpwiz.mrradb.model;


import net.stumpwiz.mrradb.model.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Raj extends SchemaImpl
{

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>raj</code>
     */
    public static final Raj RAJ = new Raj();

    /**
     * An organizational unit at Mercy Ridge.
     */
    public final Body BODY = Body.BODY;

    /**
     * The table <code>raj.office</code>.
     */
    public final Office OFFICE = Office.OFFICE;

    /**
     * A resident, staff member, or any other individual serving in some office
     * at Mercy Ridge.
     */
    public final Person PERSON = Person.PERSON;

    /**
     * VIEW
     */
    public final Pto PTO = Pto.PTO;

    /**
     * The table <code>raj.term</code>.
     */
    public final Term TERM = Term.TERM;

    /**
     * No further instances allowed
     */
    private Raj()
    {
        super("raj", null);
    }


    @Override
    public Catalog getCatalog()
    {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables()
    {
        return Arrays.asList(
                Body.BODY,
                Office.OFFICE,
                Person.PERSON,
                Pto.PTO,
                Term.TERM
        );
    }
}
