/*
 * This file is generated by jOOQ.
 */
package net.stumpwiz.mrradb.model;


import net.stumpwiz.mrradb.model.tables.*;


/**
 * Convenience access to all tables in raj.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables
{

    /**
     * An organizational unit at Mercy Ridge.
     */
    public static final Body BODY = Body.BODY;

    /**
     * The table <code>raj.office</code>.
     */
    public static final Office OFFICE = Office.OFFICE;

    /**
     * A resident, staff member, or any other individual serving in some office at Mercy Ridge.
     */
    public static final Person PERSON = Person.PERSON;

    /**
     * VIEW
     */
    public static final Pto PTO = Pto.PTO;

    /**
     * The table <code>raj.term</code>.
     */
    public static final Term TERM = Term.TERM;
}
